### ISSUE TITLE
rdf:HTML elements handled incorrectly

### ISSUE THREAD

**Issue by pietercolpaert** [pietercolpaert/rdfa-processor#4]
See https://github.com/pietercolpaert/ldfetch/issues/25 mentioned by @csarven

Changed requested: convert a DOM element into a string in order to follow the rdfjs spec over here: https://github.com/pietercolpaert/rdfa-processor/blob/master/src/RDFaProcessor.js#L839-L842

**Comment by csarven** [comment]
My memory is not serving me well because naturally I ran into this awhile back.

You might want to grab whatever you can from https://github.com/csarven/rdflib.js/commits/RDFa (it uses green-turtle's RDFaProcessor). IIRC, I've resolved the rdf:HTML issue there. Probably related: addTriple, toRDFNodeObject, Util.domToString..

(yes, I know, this should all be done upstream..)

See also latest https://github.com/linkeddata/rdflib.js/blob/master/src/rdfaparser.js .. (files moved around.. the history is a bit confusing). I don't know if anything else broke/fixed at the moment.
